# Autogenerated script from 05_bismark_array_job.R
# date Wed Aug 16 14:01:43 2017
# make sure directory paths exist before running script
#!/bin/bash
#$ -S /bin/bash
#$ -pe smp 8
#$ -cwd
#$ -N bismark-array
#$ -j y
#$ -l h_vmem=19G
#$ -t 1-8



module load bioinformatics/bowtie2/2.2.5
module load bioinformatics/samtools/1.3.1



# Parse parameter file to get variables.
number=$SGE_TASK_ID
paramfile=bismark_param.txt
 
inr1=`sed -n ${number}p $paramfile | awk '{print $1}'`
inr2=`sed -n ${number}p $paramfile | awk '{print $2}'`

# 9. Run the program.
/users/k1625253/brc_scratch/Programs/bismark_v0.18.1/bismark /users/k1625253/brc_scratch/Data/MetaData/GenomeIndex/mm10_bismark/ -1 $inr1 -2 $inr2 -p 4 --multicore 8 -o output/Aligned/ --temp_dir output/Aligned/temp/



