# Autogenerated script from write_samtools_script.R
# date Fri Sep  1 10:01:53 2017
# make sure directory paths exist before running script
#!/bin/bash
#$ -S /bin/bash
#$ -pe smp 3
#$ -cwd
#$ -N samtools-array
#$ -j y
#$ -l h_vmem=19G
#$ -t 1-8



module load bioinformatics/samtools/1.3.1
module load bioinformatics/picard-tools/2.2.1



# Parse parameter file to get variables.
number=$SGE_TASK_ID
paramfile=samtools_param.txt
 
bamfile=`sed -n ${number}p $paramfile | awk '{print $1}'`
bamq10=`sed -n ${number}p $paramfile | awk '{print $2}'`
bamq10sort=`sed -n ${number}p $paramfile | awk '{print $3}'`
bamrd=`sed -n ${number}p $paramfile | awk '{print $4}'`
rdreport=`sed -n ${number}p $paramfile | awk '{print $5}'`
bamrdsort2=`sed -n ${number}p $paramfile | awk '{print $6}'`

# 9. Run the program. NOTE: using Picard tools for coordinate sorting for bismark compatibility
samtools view -b -q 10 $bamfile > $bamq10
java -Xmx30G -jar /opt/apps/bioinformatics/picard-tools/2.2.1/picard.jar SortSam OUTPUT=$bamq10sort INPUT=$bamq10 SORT_ORDER=coordinate VALIDATION_STRINGENCY=SILENT
java -Xmx30G -jar /opt/apps/bioinformatics/picard-tools/2.2.1/picard.jar MarkDuplicates I=$bamq10sort O=$bamrd M=$rdreport REMOVE_DUPLICATES=true VALIDATION_STRINGENCY=SILENT
java -Xmx30G -jar /opt/apps/bioinformatics/picard-tools/2.2.1/picard.jar SortSam OUTPUT=$bamrdsort2 INPUT=$bamrd SORT_ORDER=queryname VALIDATION_STRINGENCY=SILENT
samtools index $bamrd



