# File: 05_bismark_array_job.R
# Auth: umar.niazi@kcl.as.uk
# DESC: create a parameter file and shell script to run array job on hpc
# Date: 18/6/2018


## set variables and source libraries
source('header.R')

## connect to mysql database to get sample information
library('RMySQL')

##### connect to mysql database to get samples
db = dbConnect(MySQL(), user='rstudio', password='12345', dbname='Projects', host='127.0.0.1')
dbListTables(db)

# check how many files each sample has
g_did
q = paste0('select count(File.idSample) as files, Sample.idData, Sample.title, Sample.id as SampleID from File, Sample
           where (Sample.idData = 27 and File.idSample = Sample.id) group by File.idSample')
dfQuery = dbGetQuery(db, q)
dfQuery$title = gsub(" ", "", dfQuery$title, fixed = T)
dfQuery

# get the count of files
q = paste0('select File.*, Sample.idData from File, Sample 
           where (Sample.idData = 27) and (File.idSample = Sample.id) ')
dfCounts = dbGetQuery(db, q)
dfCounts$name = gsub(" ", "", dfCounts$name, fixed = T)
head(dfCounts)
nrow(dfCounts)
dfCounts

# for each sample id, get the corresponding files
cvQueries = paste0('select File.*, Sample.title from File, Sample 
                   where (Sample.idData = 27 and Sample.id =', dfQuery$SampleID, ') and (File.idSample = Sample.id) ')

# set header variables 
cvShell = '#!/bin/bash'
cvShell.2 = '#$ -S /bin/bash'
cvProcessors = '#$ -pe smp 8'
cvWorkingDir = '#$ -cwd'
cvJobName = '#$ -N bismark-array'
cvStdout = '#$ -j y'
cvMemoryReserve = '#$ -l h_vmem=19G'
cvArrayJob = paste0('#$ -t 1-', nrow(dfCounts)/2)
# using high memory queue with one slot and 19 Gigs of memory

# set the directory names
cvInput = 'input/'
cvOutput = 'output/Aligned/'
cvTempDir = 'output/Aligned/temp/'
cvBismark = '/users/k1625253/brc_scratch/Programs/bismark_v0.18.1/'
cvBowtie2 = '/opt/apps/bioinformatics/bowtie2/2.2.5/bowtie2'
cvGeneIndex = '/users/k1625253/brc_scratch/Data/MetaData/GenomeIndex/mm10_bismark/'

# create a parameter file and shell script
dir.create('AutoScripts')
oFile.param = file('AutoScripts/bismark_param.txt', 'wt')

temp = sapply(cvQueries, function(x){
  # get the file names
  dfFiles = dbGetQuery(db, x)
  # check for null return
  if (nrow(dfFiles) == 0) return();
  # remove white space from title
  dfFiles$title = gsub(" ", "", dfFiles$title, fixed=T)
  # split the file names into paired end 1 and 2, identified by R1 and R2 in the file name
  f = dfFiles$name
  d = grepl('_R1_', f)
  d = as.character(d)
  d[d == 'TRUE'] = 'R1'
  d[d == 'FALSE'] = 'R2'
  lf = split(f, d)
  # write parameter file
  in.r1 = paste0(cvInput, 'trim_', lf[[1]])
  in.r2 = paste0(cvInput, 'trim_', lf[[2]])
  p1 = paste(in.r1, in.r2, sep=' ')
  writeLines(p1, oFile.param)
})

close(oFile.param)

oFile = file('AutoScripts/bismark.sh', 'wt')

writeLines(c('# Autogenerated script from 05_bismark_array_job.R', paste('# date', date())), oFile)
writeLines(c('# make sure directory paths exist before running script'), oFile)
writeLines(c(cvShell, cvShell.2, cvProcessors, cvWorkingDir, cvJobName, cvStdout, cvMemoryReserve, cvArrayJob), oFile)
writeLines('\n\n', oFile)

# module load
writeLines(c('module load bioinformatics/bowtie2/2.2.5'), oFile)
writeLines(c('module load bioinformatics/samtools/1.3.1'), oFile)
writeLines('\n\n', oFile)

## write array job lines
writeLines("# Parse parameter file to get variables.
number=$SGE_TASK_ID
paramfile=bismark_param.txt
 
inr1=`sed -n ${number}p $paramfile | awk '{print $1}'`
inr2=`sed -n ${number}p $paramfile | awk '{print $2}'`

# 9. Run the program.", oFile)
cvProg = paste(cvBismark, 'bismark', sep='')
p1 = paste(cvProg, cvGeneIndex, '-1', '$inr1', '-2', '$inr2', '-p 4', '--multicore 8', '-o', cvOutput, '--temp_dir', cvTempDir, sep=' ')
com = paste(p1)

writeLines(com, oFile)
writeLines('\n\n', oFile)

close(oFile)
dbDisconnect(db)
